# Generated by Django 3.2.7 on 2021-10-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_link', models.URLField(max_length=500, primary_key=True, serialize=False)),
                ('article_title', models.CharField(max_length=500)),
                ('article_source', models.CharField(max_length=50)),
            ],
        ),
    ]
