# Generated by Django 3.2.7 on 2021-10-05 23:29

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2021-10-05T23:31:01+00:00"),
            preserve_default=False,
        ),
    ]
