# Generated by Django 3.2.7 on 2021-10-06 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0002_article_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
    ]
